if(EXISTS "/home/r12943092/OPENROAD-Syn-TM/src/gpl/test/fft_test[1]_tests.cmake")
  include("/home/r12943092/OPENROAD-Syn-TM/src/gpl/test/fft_test[1]_tests.cmake")
else()
  add_test(fft_test_NOT_BUILT fft_test_NOT_BUILT)
endif()
