if(EXISTS "/home/r12943092/OPENROAD-Syn-TM/src/odb/test/cpp/scan/TestScanChain[1]_tests.cmake")
  include("/home/r12943092/OPENROAD-Syn-TM/src/odb/test/cpp/scan/TestScanChain[1]_tests.cmake")
else()
  add_test(TestScanChain_NOT_BUILT TestScanChain_NOT_BUILT)
endif()
