if(EXISTS "/home/r12943092/OPENROAD-Syn-TM/src/dft/test/cpp/TestScanArchitect[1]_tests.cmake")
  include("/home/r12943092/OPENROAD-Syn-TM/src/dft/test/cpp/TestScanArchitect[1]_tests.cmake")
else()
  add_test(TestScanArchitect_NOT_BUILT TestScanArchitect_NOT_BUILT)
endif()
