# CMake generated Testfile for 
# Source directory: /home/r12943092/OPENROAD-Syn-TM/src/ant/test
# Build directory: /home/r12943092/OPENROAD-Syn-TM/src/ant/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ant.check_api1 "/usr/bin/bash" "/home/r12943092/OPENROAD-Syn-TM/src/ant/test/regression" "check_api1")
set_tests_properties(ant.check_api1 PROPERTIES  ENVIRONMENT "TEST_TYPE=compare_logfile;CTEST_TESTNAME=check_api1;DIFF_LOCATION=/home/r12943092/OPENROAD-Syn-TM/src/ant/test/results/check_api1.diff" LABELS "IntegrationTest" WORKING_DIRECTORY "/home/r12943092/OPENROAD-Syn-TM/src/ant/test" _BACKTRACE_TRIPLES "/home/r12943092/OPENROAD-Syn-TM/src/cmake/testing.cmake;2;add_test;/home/r12943092/OPENROAD-Syn-TM/src/ant/test/CMakeLists.txt;12;or_integration_test;/home/r12943092/OPENROAD-Syn-TM/src/ant/test/CMakeLists.txt;0;")
add_test(ant.check_drt1 "/usr/bin/bash" "/home/r12943092/OPENROAD-Syn-TM/src/ant/test/regression" "check_drt1")
set_tests_properties(ant.check_drt1 PROPERTIES  ENVIRONMENT "TEST_TYPE=compare_logfile;CTEST_TESTNAME=check_drt1;DIFF_LOCATION=/home/r12943092/OPENROAD-Syn-TM/src/ant/test/results/check_drt1.diff" LABELS "IntegrationTest" WORKING_DIRECTORY "/home/r12943092/OPENROAD-Syn-TM/src/ant/test" _BACKTRACE_TRIPLES "/home/r12943092/OPENROAD-Syn-TM/src/cmake/testing.cmake;2;add_test;/home/r12943092/OPENROAD-Syn-TM/src/ant/test/CMakeLists.txt;12;or_integration_test;/home/r12943092/OPENROAD-Syn-TM/src/ant/test/CMakeLists.txt;0;")
add_test(ant.check_grt1 "/usr/bin/bash" "/home/r12943092/OPENROAD-Syn-TM/src/ant/test/regression" "check_grt1")
set_tests_properties(ant.check_grt1 PROPERTIES  ENVIRONMENT "TEST_TYPE=compare_logfile;CTEST_TESTNAME=check_grt1;DIFF_LOCATION=/home/r12943092/OPENROAD-Syn-TM/src/ant/test/results/check_grt1.diff" LABELS "IntegrationTest" WORKING_DIRECTORY "/home/r12943092/OPENROAD-Syn-TM/src/ant/test" _BACKTRACE_TRIPLES "/home/r12943092/OPENROAD-Syn-TM/src/cmake/testing.cmake;2;add_test;/home/r12943092/OPENROAD-Syn-TM/src/ant/test/CMakeLists.txt;12;or_integration_test;/home/r12943092/OPENROAD-Syn-TM/src/ant/test/CMakeLists.txt;0;")
add_test(ant.ant_check "/usr/bin/bash" "/home/r12943092/OPENROAD-Syn-TM/src/ant/test/regression" "ant_check")
set_tests_properties(ant.ant_check PROPERTIES  ENVIRONMENT "TEST_TYPE=compare_logfile;CTEST_TESTNAME=ant_check;DIFF_LOCATION=/home/r12943092/OPENROAD-Syn-TM/src/ant/test/results/ant_check.diff" LABELS "IntegrationTest" WORKING_DIRECTORY "/home/r12943092/OPENROAD-Syn-TM/src/ant/test" _BACKTRACE_TRIPLES "/home/r12943092/OPENROAD-Syn-TM/src/cmake/testing.cmake;2;add_test;/home/r12943092/OPENROAD-Syn-TM/src/ant/test/CMakeLists.txt;12;or_integration_test;/home/r12943092/OPENROAD-Syn-TM/src/ant/test/CMakeLists.txt;0;")
add_test(ant.ant_report "/usr/bin/bash" "/home/r12943092/OPENROAD-Syn-TM/src/ant/test/regression" "ant_report")
set_tests_properties(ant.ant_report PROPERTIES  ENVIRONMENT "TEST_TYPE=compare_logfile;CTEST_TESTNAME=ant_report;DIFF_LOCATION=/home/r12943092/OPENROAD-Syn-TM/src/ant/test/results/ant_report.diff" LABELS "IntegrationTest" WORKING_DIRECTORY "/home/r12943092/OPENROAD-Syn-TM/src/ant/test" _BACKTRACE_TRIPLES "/home/r12943092/OPENROAD-Syn-TM/src/cmake/testing.cmake;2;add_test;/home/r12943092/OPENROAD-Syn-TM/src/ant/test/CMakeLists.txt;12;or_integration_test;/home/r12943092/OPENROAD-Syn-TM/src/ant/test/CMakeLists.txt;0;")
