if(EXISTS "/home/r12943092/OPENROAD-Syn-TM/src/dpl/test/dpl_test[1]_tests.cmake")
  include("/home/r12943092/OPENROAD-Syn-TM/src/dpl/test/dpl_test[1]_tests.cmake")
else()
  add_test(dpl_test_NOT_BUILT dpl_test_NOT_BUILT)
endif()
