if(EXISTS "/home/r12943092/OPENROAD-Syn-TM/src/mpl2/test/cpp/TestSnapper[1]_tests.cmake")
  include("/home/r12943092/OPENROAD-Syn-TM/src/mpl2/test/cpp/TestSnapper[1]_tests.cmake")
else()
  add_test(TestSnapper_NOT_BUILT TestSnapper_NOT_BUILT)
endif()
